<a href="https://colab.research.google.com/github/Brundavathi/Computational-Mathematics/blob/main/Linear_Algebra_System_of_Linear_Equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

###Solving Linear System of Equations
x + y + z = 3<br/>
2x + 3y + 7z = 0<br/>
x + 3y - 2z = 17

In [ ]:
A = np.array([[1,1,1],[2,3,7],[1,3,-2]])
A

array([[ 1,  1,  1],
       [ 2,  3,  7],
       [ 1,  3, -2]])

In [ ]:
B = np.array([3,0,17])
B

array([ 3,  0, 17])

In [ ]:
np.linalg.solve(A,B)

array([ 1.,  4., -2.])

In [ ]:
#Rank of Matrices

np.linalg.matrix_rank(A)

3

In [ ]:
D = np.array([[1,1,1],[2,3,7],[0,0,0]])
np.linalg.matrix_rank(D)

2

In [ ]:
#Eigen Value

E = np.array([[-6,3],[4,5]])
E

array([[-6,  3],
       [ 4,  5]])

In [ ]:
W,V = np.linalg.eig(E)
W  # Eigen Values

array([-7.,  6.])

In [ ]:
V # Eigen Vector

array([[-0.9486833 , -0.24253563],
       [ 0.31622777, -0.9701425 ]])

In [ ]:
np.multiply(W,V) # Multiply Eigen vector with Eigen Value

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [ ]:
np.matmul(E,V) #Multiply Matrix with Eigen Vector

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])