<a href="https://colab.research.google.com/github/Brundavathi/Computational-Mathematics/blob/main/Linear_Algebra_Scalars_and_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.isscalar(26)

True

In [ ]:
np.isscalar(26.5)

True

In [ ]:
np.isscalar(False) # Boolean  0 or 1, single magnitude

True

In [ ]:
np.isscalar([26]) # list and can hold multiple values

False

In [ ]:
#Scalar Computation

S1 = 6
S2 = 4
print(S1+S2)
print(S1-S2)
print(S1*S2)
print(S1/S2)
print(S1//S2) # Floor Division


10
2
24
1.5
1


In [ ]:
# Vector

a = [1,2,3]
a * 2 # Incorrect

[1, 2, 3, 1, 2, 3]

In [ ]:
#Multiply a Vector by a Scalar

np.array(a) * 2

array([2, 4, 6])

In [ ]:
np.multiply(a,2)

array([2, 4, 6])

In [ ]:
# Adding a vector by scalar

np.array(a) + 2
np.add(a,2)

array([3, 4, 5])

In [ ]:
# Vector Subtraction

np.array(a) - 2
np.subtract(a,2)

array([-1,  0,  1])

In [ ]:
# Multiple Vector

a = [10,15,18]
b = [11,23,45]

In [ ]:
np.add(a,b)

array([21, 38, 63])

In [ ]:
np.subtract(a,b)

array([ -1,  -8, -27])

In [ ]:
a = np.array([10,15,18])
b = np.array([11,23,45])

a - b

array([ -1,  -8, -27])

In [ ]:
# Dot product of two vectors

np.dot(a,b)

1265

In [ ]:
np.cross(a,b)

array([ 261, -252,   65])

In [ ]:
# Magnitude of a vector

np.linalg.norm(a)

25.475478405713993