<a href="https://colab.research.google.com/github/Brundavathi/Computational-Mathematics/blob/main/Linear_Algebra_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[3,4],[2,1]])
B = np.array([[1,5],[3,7]])
print('A : \n',A)
print('B : \n',B)

A : 
 [[3 4]
 [2 1]]
B : 
 [[1 5]
 [3 7]]


In [ ]:
# Addition/Subtraction of Matrices

A + B
A - B 

array([[ 2, -1],
       [-1, -6]])

In [ ]:
np.add(A,B)
np.subtract(A,B)

array([[ 2, -1],
       [-1, -6]])

In [ ]:
# Scalar Addition/Subtraction/Multiplication

A * 2
np.multiply(A,2)

array([[6, 8],
       [4, 2]])

In [ ]:
A * 1/2

array([[1.5, 2. ],
       [1. , 0.5]])

In [ ]:
A + 2
np.add(A,2)

A - 2
np.subtract(A,2)

array([[ 1,  2],
       [ 0, -1]])

In [ ]:
# Matrix Multiplication

print('A : \n',A)
print('B : \n',B)

A : 
 [[3 4]
 [2 1]]
B : 
 [[1 5]
 [3 7]]


In [ ]:
np.matmul(A,B)

array([[15, 43],
       [ 5, 17]])

In [ ]:
C = np.array([[3,4,2]])
D = np.array([[13,9,7,15],[8,7,4,6],[6,4,0,3]])
print('C : \n',C,'Shape: ',C.shape)
print('D : \n',D,'Shape: ',D.shape)  # Output : M * N = N * P

C : 
 [[3 4 2]] Shape:  (1, 3)
D : 
 [[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]] Shape:  (3, 4)


In [ ]:
np.matmul(C,D)

array([[83, 63, 37, 75]])

In [ ]:
#Matrix Multiplication is not commutative

E = np.array([[1,1],[100,100]])
F = np.array([[-1,1],[1,-1]])
np.matmul(E,F)

array([[0, 0],
       [0, 0]])

In [ ]:
np.matmul(F,E)

array([[ 99,  99],
       [-99, -99]])

In [ ]:
#Matrix Transpose - Row to columns

np.transpose(A)

array([[3, 2],
       [4, 1]])

In [ ]:
A.T

array([[3, 2],
       [4, 1]])

In [ ]:
np.transpose(np.transpose(A)) # Transfer two Matrices

array([[3, 4],
       [2, 1]])

###Transposition Rule
(AB)T = BT * AT  
HERE T stands for Transpose


In [ ]:
print('A : \n',A)
print('B : \n',B)

A : 
 [[3 4]
 [2 1]]
B : 
 [[1 5]
 [3 7]]


In [ ]:
matrix_mul = np.matmul(A,B)
np.transpose(matrix_mul)

array([[15,  5],
       [43, 17]])

In [ ]:
np.matmul(B.T,A.T)

array([[15,  5],
       [43, 17]])

In [ ]:
#Special Matrices

#Symmetric

sMatrix = np.array([[1,1,-1],[1,2,0],[-1,0,5]])
sMatrix

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [ ]:
sMatrix.T #After transpose gives same matrix

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [ ]:
#Skew Matrix

skMatrix = np.array([[0,1,-2],[-1,0,3],[2,-3,0]])
skMatrix

array([[ 0,  1, -2],
       [-1,  0,  3],
       [ 2, -3,  0]])

In [ ]:
skMatrix.T      #Transpose gives negative values

array([[ 0, -1,  2],
       [ 1,  0, -3],
       [-2,  3,  0]])

In [ ]:
# Diagonal Matrix

dMatrix = np.array([[12,0,0],[0,18,0],[0,0,26]])
dMatrix

array([[12,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 26]])

In [ ]:
# Covert a vector to diagonal Matrix

a = np.array([12,18,26]) #single vector converted to diagonal
np.diag(a)

array([[12,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 26]])

In [ ]:
#Finding Determinant of a Matrix

mat = np.array([[3,1],[1,2]])
mat

array([[3, 1],
       [1, 2]])

In [ ]:
np.linalg.det(mat)

5.000000000000001

In [ ]:
mat2 = np.array([[2,-3,1],[2,0,-1],[1,4,5]])
mat2

array([[ 2, -3,  1],
       [ 2,  0, -1],
       [ 1,  4,  5]])

In [ ]:
sol = np.linalg.det(mat2)
sol 

49.000000000000014

In [ ]:
np.around(sol)

49.0

In [ ]:
np.linalg.det(mat.T)

5.000000000000001

In [ ]:
A

array([[3, 4],
       [2, 1]])

In [ ]:
# Identity Matrix

id_mat = np.array([[1,0],[0,1]])
id_mat

array([[1, 0],
       [0, 1]])

In [ ]:
np.matmul(A,id_mat)

array([[3, 4],
       [2, 1]])

In [ ]:
#Inverse of a Matrix

A_inv = np.linalg.inv(A)
A_inv

array([[-0.2,  0.8],
       [ 0.4, -0.6]])

In [ ]:
# A * A_inv = I

np.matmul(A,A_inv)

array([[1., 0.],
       [0., 1.]])